# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# waste less space
general {
    gaps_in = 1
    gaps_out = 1
    border_size = 1
}

windowrule = float on, match:class org.omarchy.runner
windowrule = center on, match:class org.omarchy.runner
windowrule = size 900 260, match:class org.omarchy.runner
windowrule = opacity 1 1, match:tag default-opacity
windowrule = opacity 1 1, match:tag terminal
windowrule = opacity 1 1, match:tag chromium-based-browser
windowrule = opacity 1 1, match:tag firefox-based-browser

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
