#!/usr/bin/env python3
import os, sys, requests, re
from pathlib import Path
from bs4 import BeautifulSoup
from urllib.parse import urljoin

#%%
def scrape_links(url, pat = ".pdf"):
    """
    Scrapes all links on page, optionally accepts filename pattern.
    Uses requests and BeautifulSoup.
    """
    try:
        # Fetch the content of the URL
        response = requests.get(url)
        # Raise an exception for bad status codes (4xx or 5xx)
        response.raise_for_status()

        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find all anchor tags with an href attribute
        all_links = soup.find_all('a', href=True)

        absolute_links = []
        for link in all_links:
            # Convert relative URLs to absolute URLs
            absolute_link = urljoin(url, link['href'])
            absolute_links.append(absolute_link)

        if pat:
            # Filter links based on the provided pattern
            filtered_links = [link for link in absolute_links if re.search(pat, link)]
            return filtered_links

        return absolute_links

    except requests.exceptions.RequestException as e:
        print(f"Error during requests to {url} : {e}")
        return []


# %%
def download(url):
    try:
        fn = url.rsplit('/', 1)[-1]
        r = requests.get(url)
        with open(fn,'wb') as f:
            f.write(r.content)
        print(url.rsplit('/', 1)[-1] + ' download successful.')
    except:
        print(url.rsplit('/', 1)[-1] + ' failed to download.')
        pass

def download_files(filelist, targetdir):
    """
    creates output folder and calls download to dl files from list
    to specified location
    """
    cwd = os.getcwd()
    if targetdir:
        Path(targetdir).mkdir(parents = True, exist_ok = True)
        os.chdir(targetdir)
    for f in filelist:
        download(f)
    os.chdir(cwd)

def unwebsitifier(link):
    """
    removes website prefixes / shortens URL to conform to windows' folder
    name limits
    """
    folder = re.sub(r'http|https|.edu|.org|[^\w]', '', link)
    return (folder[-20:])

# %%
if __name__ == '__main__':
    print('script call format: /getter2 <url>')
    link = sys.argv[1]
    foldername = (unwebsitifier(link))
    if len(sys.argv) > 2: # filename pattern specified
        ext = sys.argv[2]
        print(f'downloading {ext} pattern from link')
        linklist = scrape_links(link, pat = ext)
    else: # defaults to pdf
        print('downloading from : ', link)
        linklist = scrape_links(link)
    download_files(filelist=linklist, targetdir = foldername)
